# Copyright (c) 2019-2020 Luca Cappa
# Released under the term specified in file LICENSE.txt
# SPDX short identifier: MIT
name: build-cnconline-forwarder-x
on: [push, workflow_dispatch]

jobs:
  job:
    name: ${{ matrix.os }}-hosted-basic
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: windows-latest
            triplet: x64-windows
            vcpkgCommitId: 7e94e6d35762949e6de72d9526807006ccc98b57
            vcpkgPackages: 'boost-algorithm boost-asio boost-beast boost-container-hash boost-endian boost-log boost-system boost-test'
            artifactId: windows-built-files
          - os: ubuntu-latest
            triplet: x64-linux
            vcpkgCommitId: 7e94e6d35762949e6de72d9526807006ccc98b57
            vcpkgPackages: 'boost-algorithm boost-asio boost-beast boost-container-hash boost-endian boost-log boost-system boost-test'
            artifactId: ubuntu-built-files

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - uses: lukka/get-cmake@latest
      - name: 'Restore artifacts, or run vcpkg, build and cache artifacts'
        uses: lukka/run-vcpkg@v7
        id: runvcpkg
        with:
          vcpkgArguments: '${{ matrix.vcpkgPackages }}'
          vcpkgTriplet: '${{ matrix.triplet }}'
          vcpkgDirectory: '${{ runner.workspace }}/b/vcpkg'
          vcpkgGitCommitId: '${{ matrix.vcpkgCommitId }}'
      - name: Run CMake+Ninja without triplet
        uses: lukka/run-cmake@v3
        id: runcmake
        with:
          cmakeGenerator: 'Ninja'  
          cmakeListsOrSettingsJson: 'CMakeListsTxtBasic'
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          cmakeBuildType: Release
          useVcpkgToolchainFile: true
          buildWithCMakeArgs: '-- -v'
          buildDirectory: '${{ runner.workspace }}/b/ninja/'
      - name: Upload Windows build artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          # Artifact name
          name: '${{ matrix.artifactId }}' # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: |
            ${{ runner.workspace }}/b/ninja/CNCOnlineForwarder*/*
            !${{ runner.workspace }}/b/ninja/CNCOnlineForwarder*/*cmake*
            !${{ runner.workspace }}/b/ninja/CNCOnlineForwarder*/CMakeFiles/**/*
